/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pavel_dbtojava_DbApiMaster */

#ifndef _Included_com_pavel_dbtojava_DbApiMaster
#define _Included_com_pavel_dbtojava_DbApiMaster
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_pavel_dbtojava_ShortModel
 * Method:    getModelName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pavel_dbtojava_ShortModel_getModelName
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_pavel_dbtojava_ShortModel
 * Method:    getModelSmallpicture
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pavel_dbtojava_ShortModel_getModelSmallpicture
  (JNIEnv *, jobject, jint);

	
/*
 * Class:     com_pavel_dbtojava_DbApiMaster
 * Method:    getTotalRowsNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_pavel_dbtojava_DbApiMaster_getTotalRowsNumber
  (JNIEnv *, jobject);

/*
 * Class:     com_pavel_dbtojava_DbApiMaster
 * Method:    getTotalRowsNumberLike
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_pavel_dbtojava_DbApiMaster_getTotalRowsNumberLike
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_pavel_dbtojava_DbApiMaster
 * Method:    getAllSmallModels
 * Signature: (Lcom/pavel/dbtojava/ShortModel;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_pavel_dbtojava_DbApiMaster_getAllSmallModels
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif