/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orcchg_javacourse_NativeFour */

#ifndef _Included_com_orcchg_javacourse_NativeFour
#define _Included_com_orcchg_javacourse_NativeFour
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_orcchg_javacourse_NativeFour
 * Method:    distance
 * Signature: (Lcom/orcchg/javacourse/Point;Lcom/orcchg/javacourse/Point;)F
 */
JNIEXPORT jfloat JNICALL Java_com_orcchg_javacourse_NativeFour_distance
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
