/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orcchg_javacourse_NativeOne */

#ifndef _Included_com_orcchg_javacourse_NativeOne
#define _Included_com_orcchg_javacourse_NativeOne
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_orcchg_javacourse_NativeOne
 * Method:    calculate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_orcchg_javacourse_NativeOne_calculate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
