/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orcchg_javacourse_NativeTwo */

#ifndef _Included_com_orcchg_javacourse_NativeTwo
#define _Included_com_orcchg_javacourse_NativeTwo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_orcchg_javacourse_NativeTwo
 * Method:    distance
 * Signature: (FFFF)F
 */
JNIEXPORT jfloat JNICALL Java_com_orcchg_javacourse_NativeTwo_distance
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
