/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orcchg_javacourse_NativeThree */

#ifndef _Included_com_orcchg_javacourse_NativeThree
#define _Included_com_orcchg_javacourse_NativeThree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_orcchg_javacourse_NativeThree
 * Method:    reverseString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_orcchg_javacourse_NativeThree_reverseString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
