/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_orcchg_javacourse_NativeFive */

#ifndef _Included_com_orcchg_javacourse_NativeFive
#define _Included_com_orcchg_javacourse_NativeFive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_orcchg_javacourse_NativeFive
 * Method:    call
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_orcchg_javacourse_NativeFive_call
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
